// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type FileStashUrl struct {
	ID                int32
	Url               string
	CreatedAt         sql.NullTime
	SingleRowEnforcer int32
}

type RabbitMqConfig struct {
	ConnUrl           string
	Username          string
	Password          string
	CreatedAt         sql.NullTime
	SingleRowEnforcer int32
}
