// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type FileStashUrl struct {
	ID                int32
	Url               string
	CreatedAt         sql.NullTime
	SingleRowEnforcer int32
}

type InfluxdbConfiguration struct {
	ID                   int32
	Type                 string
	DatabaseName         string
	Host                 string
	Port                 int32
	User                 string
	Password             string
	Organization         string
	SslEnabled           bool
	BatchSize            int32
	RetryInterval        string
	RetryExponentialBase int32
	MaxRetries           int32
	MaxRetryTime         string
	MetaAsTags           sql.NullString
	SingleRowEnforcer    int32
}

type LogicalVolume struct {
	LvID      int32
	MachineID string
	LvName    string
	VgName    string
	LvAttr    string
	LvSize    string
	CreatedAt sql.NullTime
}

type LvStorageIssuer struct {
	ID                  int32
	MachineID           string
	IncBuffer           sql.NullInt32
	DecBuffer           sql.NullInt32
	Hostname            string
	Username            string
	Minavailablespacegb float64
	Maxavailablespacegb float64
}

type LvmConf struct {
	ID                  int32
	MachineID           string
	Username            string
	Minavailablespacegb float64
	Maxavailablespacegb float64
	CreatedAt           sql.NullTime
}

type Machine struct {
	MachineID string
	Hostname  string
	OsVersion string
	IpAddress string
	CreatedAt sql.NullTime
}

type MachineConf struct {
	ID         int32
	MachineID  string
	Hostname   string
	Username   string
	Passphrase sql.NullString
	PortNumber int32
	Password   sql.NullString
	HostKey    sql.NullString
	FolderPath sql.NullString
}

type Notification struct {
	ID        int32
	Message   string
	CreatedAt sql.NullTime
}

type PhysicalVolume struct {
	PvID      int32
	MachineID string
	PvName    string
	VgName    string
	PvFmt     string
	PvAttr    string
	PvSize    string
	PvFree    string
	CreatedAt sql.NullTime
}

type RabbitMqConfig struct {
	ConnUrl           string
	Username          string
	Password          string
	CreatedAt         sql.NullTime
	SingleRowEnforcer int32
}

type RealtimeLog struct {
	ID         int32
	LogMessage string
	MachineID  string
	CreatedAt  sql.NullTime
}

type VolumeGroup struct {
	VgID      int32
	MachineID string
	VgName    string
	PvCount   string
	LvCount   string
	SnapCount string
	VgAttr    string
	VgSize    string
	VgFree    string
	CreatedAt sql.NullTime
}
