// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateFileStashURL(ctx context.Context) error
	CreateInfluxDBConfiguration(ctx context.Context) error
	CreateLVMConf(ctx context.Context) error
	CreateLVStorageIssuer(ctx context.Context) error
	CreateLogicalVolume(ctx context.Context) error
	CreateMachine(ctx context.Context) error
	CreateMachineConf(ctx context.Context) error
	CreateNotification(ctx context.Context) error
	CreatePhysicalVolume(ctx context.Context) error
	CreateRabbitMQConfig(ctx context.Context) error
	CreateRealtimeLog(ctx context.Context) error
	CreateVolumeGroup(ctx context.Context) error
	DeleteFileStashURLByID(ctx context.Context) error
	DeleteInfluxDBConfigurationByID(ctx context.Context) error
	DeleteLVMConfByID(ctx context.Context) error
	DeleteLVStorageIssuerByID(ctx context.Context) error
	DeleteLogicalVolumeByID(ctx context.Context) error
	DeleteMachineByID(ctx context.Context) error
	DeleteMachineConfByID(ctx context.Context) error
	DeleteNotificationByID(ctx context.Context) error
	DeletePhysicalVolumeByID(ctx context.Context) error
	DeleteRabbitMQConfig(ctx context.Context) error
	DeleteRealtimeLogByID(ctx context.Context) error
	DeleteVolumeGroupByID(ctx context.Context) error
	GetFileStashURLByID(ctx context.Context) (GetFileStashURLByIDRow, error)
	GetInfluxDBConfigurationByID(ctx context.Context) (InfluxdbConfiguration, error)
	GetLVMConfByID(ctx context.Context) (GetLVMConfByIDRow, error)
	GetLVStorageIssuerByID(ctx context.Context) (GetLVStorageIssuerByIDRow, error)
	GetLogicalVolumeByID(ctx context.Context) (GetLogicalVolumeByIDRow, error)
	GetMachineByID(ctx context.Context) (GetMachineByIDRow, error)
	GetMachineConfByID(ctx context.Context) (MachineConf, error)
	GetNotificationByID(ctx context.Context) (Notification, error)
	GetPhysicalVolumeByID(ctx context.Context) (GetPhysicalVolumeByIDRow, error)
	GetRabbitMQConfig(ctx context.Context) (GetRabbitMQConfigRow, error)
	GetRealtimeLogByID(ctx context.Context) (GetRealtimeLogByIDRow, error)
	GetVolumeGroupByID(ctx context.Context) (GetVolumeGroupByIDRow, error)
	ListFileStashURLs(ctx context.Context) ([]ListFileStashURLsRow, error)
	ListInfluxDBConfigurations(ctx context.Context) ([]InfluxdbConfiguration, error)
	ListLVMConfs(ctx context.Context) ([]ListLVMConfsRow, error)
	ListLVStorageIssuers(ctx context.Context) ([]ListLVStorageIssuersRow, error)
	ListLogicalVolumes(ctx context.Context) ([]ListLogicalVolumesRow, error)
	ListMachineConfs(ctx context.Context) ([]MachineConf, error)
	ListMachines(ctx context.Context) ([]ListMachinesRow, error)
	ListNotifications(ctx context.Context) ([]Notification, error)
	ListPhysicalVolumes(ctx context.Context) ([]ListPhysicalVolumesRow, error)
	ListRealtimeLogs(ctx context.Context) ([]ListRealtimeLogsRow, error)
	ListVolumeGroups(ctx context.Context) ([]ListVolumeGroupsRow, error)
	UpdateRabbitMQConfig(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
